using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using JTLanguageModelsPortable.ObjectInterfaces;
using JTLanguageModelsPortable.Object;
using JTLanguageModelsPortable.Dictionary;
using JTLanguageModelsPortable.Language;
using JTLanguageModelsPortable.Repository;

namespace JTLanguageModelsPortable.Converters
{
    public class ConvertRomaji : ConvertRomanization
    {
        private static Dictionary<string, string> _TheTableDictionary;
        private static HashSet<char> _TheCharacterSet;
        private static int _TheMaxInputLength = -1;
        private static int _TheMaxOutputLength = -1;
        private static LanguageTool _TheLanguageTool = null;

        public ConvertRomaji(
                LanguageID sourceLanguage,
                char symbolSeparator,
                DictionaryRepository dictionary,
                bool useQuickDictionary)
            : base(
                TheTablePairs,
                TheTableDictionary,
                TheCharacters,
                TheCharacterSet,
                sourceLanguage,
                LanguageLookup.JapaneseRomaji,
                symbolSeparator,
                dictionary,
                useQuickDictionary,
                TheMaxInputLength,
                TheMaxOutputLength)
        {
            InsertWordSpace = true;
            ToTableIsAmbiguous = true;
            FromTableIsAmbiguous = true;

            if (_TheLanguageTool == null)
                _TheLanguageTool = new JapaneseToolCode();

            Tool = _TheLanguageTool;
        }

        public override string PostTo(string output)
        {
            int index;

            while ((index = output.IndexOf("~tsu")) != -1)
            {
                if (index + 4 < output.Length)
                {
                    if (output[index + 4] == ' ')
                        output = output.Substring(0, index) + output.Substring(index + 5, 1) + output.Substring(index + 5);
                    else
                        output = output.Substring(0, index) + output.Substring(index + 4, 1) + output.Substring(index + 4);
                }
                else
                    break;
            }

            return output;
        }

        public static bool IsAllKana(string input)
        {
            if (String.IsNullOrEmpty(input))
                return true;

            int count = input.Length;
            int index;

            for (index = 0; index < count; index++)
            {
                char c = input[index];
                // If double marker...
                if (c == 'ー')
                    continue;
                if (c == '[')
                    TextUtilities.SkipTo(input, ']', ref index);
                else if (c == '<')
                    TextUtilities.SkipTo(input, '>', ref index);
                else if ((c < ' ') || (c > '~'))
                {
                    if (!TheCharacters.Contains(c) && !LanguageLookup.SpaceAndPunctuationCharacters.Contains(c))
                        return false;
                }
                else
                    return false;
            }

            return true;
        }

        public static bool IsAllRomaji(string input)
        {
            if (String.IsNullOrEmpty(input))
                return true;

            int count = input.Length;
            int index;

            for (index = 0; index < count; index++)
            {
                char c = input[index];
                // If double marker...
                if (c == '[')
                    TextUtilities.SkipTo(input, ']', ref index);
                else if (c == '<')
                    TextUtilities.SkipTo(input, '>', ref index);
                else if ((c < ' ') || (c > '~'))
                {
                    if (!RomajiCharacters.Contains(c) && !LanguageLookup.SpaceAndPunctuationCharacters.Contains(c))
                        return false;
                }
            }

            return true;
        }

        public static bool IsKana(char chr)
        {
            // If double marker...
            if (chr == 'ー')
                return true;
            if ((chr < ' ') || (chr > '~'))
            {
                if (TheCharacters.Contains(chr))
                    return true;
            }

            return false;
        }

        public static bool IsKatakana(char chr)
        {
            // If double marker...
            if (chr == 'ー')
                return true;
            if ((chr < ' ') || (chr > '~'))
            {
                if (KatakanaCharacters.Contains(chr))
                    return true;
            }

            return false;
        }

        public static bool IsRomaji(char chr)
        {
            if ((chr < ' ') || (chr > '~'))
            {
                if (!RomajiCharacters.Contains(chr))
                    return false;
            }

            return true;
        }

        public static bool IsCompound(string input)
        {
            if (String.IsNullOrEmpty(input))
                return true;

            bool hasKana = false;
            bool hasRomaji = false;

            int count = input.Length;
            int index;

            for (index = 0; index < count; index++)
            {
                char c = input[index];
                // If double marker...
                if (c == 'ー')
                    continue;
                if (c == '[')
                    TextUtilities.SkipTo(input, ']', ref index);
                else if (c == '<')
                    TextUtilities.SkipTo(input, '>', ref index);
                else if ((c < ' ') || LanguageLookup.SpaceAndPunctuationCharacters.Contains(c))
                    continue;
                else if (c > '~')
                {
                    if (!TheCharacters.Contains(c))
                    {
                        if (hasKana || hasRomaji)
                            return true;
                    }
                    else
                        hasKana = true;
                }
                else
                    hasRomaji = true;
            }

            return false;
        }

        public static bool IsAllKanaOrRomaji(string input)
        {
            if (String.IsNullOrEmpty(input))
                return true;

            int count = input.Length;
            int index;

            for (index = 0; index < count; index++)
            {
                char c = input[index];
                // If double marker...
                if (c == 'ー')
                    continue;
                if (c == '[')
                    TextUtilities.SkipTo(input, ']', ref index);
                else if (c == '<')
                    TextUtilities.SkipTo(input, '>', ref index);
                else if ((c < ' ') || (c > '~'))
                {
                    if (!TheCharacters.Contains(c) &&
                            !RomajiCharacters.Contains(c) &&
                            !LanguageLookup.SpaceAndPunctuationCharacters.Contains(c))
                        return false;
                }
            }

            return true;
        }

        public override bool IsAllNonRomanizedPhonetic(string input)
        {
            return IsAllKana(input);
        }

        public override bool IsAllRomanizedPhonetic(string input)
        {
            return IsAllRomaji(input);
        }

        public override bool IsAllPhonetic(string input)
        {
            return IsAllKanaOrRomaji(input);
        }

        public static string[] TheTablePairs =
        {
            "あ", "a",
            "い", "i",
            "う", "u",
            "え", "e",
            "お", "o",
            "か", "ka",
            "き", "ki",
            "く", "ku",
            "け", "ke",
            "こ", "ko",
            "さ", "sa",
            "し", "shi",
            "す", "su",
            "せ", "se",
            "そ", "so",
            "た", "ta",
            "ち", "chi",
            "つ", "tsu",
            "て", "te",
            "と", "to",
            "な", "na",
            "に", "ni",
            "ぬ", "nu",
            "ね", "ne",
            "の", "no",
            "は", "ha",
            "ひ", "hi",
            "ふ", "fu",
            "へ", "he",
            "ほ", "ho",
            "ま", "ma",
            "み", "mi",
            "む", "mu",
            "め", "me",
            "も", "mo",
            "や", "ya",
            "ゆ", "yu",
            "よ", "yo",
            "ら", "ra",
            "り", "ri",
            "る", "ru",
            "れ", "re",
            "ろ", "ro",
            "わ", "wa",
            "を", "wo",
            "ん", "n",
            "が", "ga",
            "ぎ", "gi",
            "ぐ", "gu",
            "げ", "ge",
            "ご", "go",
            "ざ", "za",
            "じ", "ji",
            "ず", "zu",
            "ぜ", "ze",
            "ぞ", "zo",
            "だ", "da",
            "ぢ", "dzi",
            "づ", "dzu",
            "で", "de",
            "ど", "do",
            "ば", "ba",
            "び", "bi",
            "ぶ", "bu",
            "べ", "be",
            "ぼ", "bo",
            "ぱ", "pa",
            "ぴ", "pi",
            "ぷ", "pu",
            "ぺ", "pe",
            "ぽ", "po",
            "きゃ", "kya",
            "きゅ", "kyu",
            "きょ", "kyo",
            "ぎゃ", "gya",
            "ぎゅ", "gyu",
            "ぎょ", "gyo",
            "しゃ", "sha",
            "しゅ", "shu",
            "しょ", "sho",
            "じゃ", "ja",
            "じゅ", "ju",
            "じょ", "jo",
            "ちゃ", "cha",
            "ちゅ", "chu",
            "ちょ", "cho",
            "にゃ", "nya",
            "にゅ", "nyu",
            "にょ", "nyo",
            "ひゃ", "hya",
            "ひゅ", "hyu",
            "ひょ", "hyo",
            "びゃ", "bya",
            "びゅ", "byu",
            "びょ", "byo",
            "ぴゃ", "pya",
            "ぴゅ", "pyu",
            "ぴょ", "pyo",
            "みゃ", "mya",
            "みゅ", "myu",
            "みょ", "myo",
            "りゃ", "rya",
            "りゅ", "ryu",
            "りょ", "ryo",

            "ああ", "ā",
            "いい", "ī",
            "うう", "ū",
            "えい", "ei",
            "ええ", "ē",
            "おう", "ou",
            "おお", "ō",
            "かあ", "kā",
            "きい", "kī",
            "くう", "kū",
            "けい", "kei",
            "けえ", "kē",
            "こう", "kou",
            "こお", "kō",
            "さあ", "sā",
            "しい", "shī",
            "すう", "suu",
            "せい", "sei",
            "せえ", "sē",
            "そう", "sou",
            "そお", "sō",
            "たあ", "tā",
            "ちい", "chī",
            "つう", "tsū",
            "てい", "tei",
            "てえ", "tē",
            "とう", "tou",
            "とお", "tō",
            "なあ", "nā",
            "にい", "nī",
            "ぬう", "nū",
            "ねい", "nei",
            "ねえ", "nē",
            "のう", "nou",
            "のお", "nō",
            "はあ", "hā",
            "ひい", "hī",
            "ふう", "fū",
            "へい", "hei",
            "へえ", "hē",
            "ほう", "hou",
            "ほお", "hō",
            "まあ", "mā",
            "みい", "mī",
            "むう", "mū",
            "めい", "mei",
            "めえ", "mē",
            "もう", "mou",
            "もお", "mō",
            "やあ", "yā",
            "ゆう", "yū",
            "よう", "you",
            "よお", "yō",
            "らあ", "rā",
            "りい", "rī",
            "るう", "rū",
            "れい", "rei",
            "れえ", "rē",
            "ろう", "rou",
            "ろお", "rō",
            "わあ", "wā",
            "があ", "gā",
            "ぎい", "gī",
            "ぐう", "gū",
            "げい", "gei",
            "げえ", "gē",
            "ごう", "gou",
            "ごお", "gō",
            "ざあ", "zā",
            "じい", "jī",
            "ずう", "zū",
            "ぜい", "zei",
            "ぜえ", "zē",
            "ぞう", "zou",
            "ぞお", "zō",
            "だあ", "dā",
            "ぢい", "dzī",
            "づう", "dzū",
            "でい", "dei",
            "でえ", "dē",
            "どう", "dou",
            "どお", "dō",
            "ばあ", "bā",
            "びい", "bī",
            "ぶう", "bū",
            "べい", "bei",
            "べえ", "bē",
            "ぼう", "bou",
            "ぼお", "bō",
            "ぱあ", "pā",
            "ぴい", "pī",
            "ぷう", "pū",
            "ぺい", "pei",
            "ぺえ", "pē",
            "ぽう", "pou",
            "ぽお", "pō",
            "きゃあ", "kyā",
            "きゅう", "kyū",
            "きょう", "kyou",
            "きょお", "kyō",
            "ぎゃあ", "gyā",
            "ぎゅう", "gyū",
            "ぎょう", "gyou",
            "ぎょお", "gyō",
            "しゃあ", "shā",
            "しゅう", "shū",
            "しょう", "shou",
            "しょお", "shō",
            "じゃあ", "jā",
            "じゅう", "jū",
            "じょう", "jou",
            "じょお", "jō",
            "ちゃあ", "chā",
            "ちゅう", "chū",
            "ちょう", "chou",
            "ちょお", "chō",
            "にゃあ", "nyā",
            "にゅう", "nyū",
            "にょう", "nyou",
            "にょお", "nyō",
            "ひゃあ", "hyā",
            "ひゅう", "hyū",
            "ひょう", "hyou",
            "ひょお", "hyō",
            "びゃあ", "byā",
            "びゅう", "byū",
            "びょう", "byou",
            "びょお", "byō",
            "ぴゃあ", "pyā",
            "ぴゅう", "pyū",
            "ぴょう", "pyou",
            "ぴょお", "pyō",
            "みゃあ", "myā",
            "みゅう", "myū",
            "みょう", "myou",
            "みょお", "myō",
            "りゃあ", "ryā",
            "りゅう", "ryū",
            "りょう", "ryou",
            "りょお", "ryō",
            "くぁ", "kwa",
            "ぐぁ", "gwa",
            "くゎ", "kwa",
            "ぐゎ", "gwa",

            "っか", "kka",
            "っき", "kki",
            "っく", "kku",
            "っけ", "kke",
            "っこ", "kko",
            "っさ", "ssa",
            "っし", "sshi",
            "っす", "ssu",
            "っせ", "sse",
            "っそ", "sso",
            "った", "tta",
            "っち", "cchi",
            "っつ", "ttsu",
            "って", "tte",
            "っと", "tto",
            "っな", "nna",
            "っに", "nni",
            "っぬ", "nnu",
            "っね", "nne",
            "っの", "nno",
            "っは", "hha",
            "っひ", "hhi",
            "っふ", "ffu",
            "っへ", "hhe",
            "っほ", "hho",
            "っま", "mma",
            "っみ", "mmi",
            "っむ", "mmu",
            "っめ", "mme",
            "っも", "mmo",
            "っや", "yya",
            "っゆ", "yyu",
            "っよ", "yyo",
            "っら", "rra",
            "っり", "rri",
            "っる", "rru",
            "っれ", "rre",
            "っろ", "rro",
            "っわ", "wwa",
            "っを", "wwo",
            "っが", "gga",
            "っぎ", "ggi",
            "っぐ", "ggu",
            "っげ", "gge",
            "っご", "ggo",
            "っざ", "zza",
            "っじ", "jji",
            "っず", "zzu",
            "っぜ", "zze",
            "っぞ", "zzo",
            "っだ", "dda",
            "っぢ", "ddzi",
            "っづ", "ddzu",
            "っで", "dde",
            "っど", "ddo",
            "っば", "bba",
            "っび", "bbi",
            "っぶ", "bbu",
            "っべ", "bbe",
            "っぼ", "bbo",
            "っぱ", "ppa",
            "っぴ", "ppi",
            "っぷ", "ppu",
            "っぺ", "ppe",
            "っぽ", "ppo",
            "っきゃ", "kkya",
            "っきゅ", "kkyu",
            "っきょ", "kkyo",
            "っぎゃ", "ggya",
            "っぎゅ", "ggyu",
            "っぎょ", "ggyo",
            "っしゃ", "ssha",
            "っしゅ", "sshu",
            "っしょ", "ssho",
            "っじゃ", "jja",
            "っじゅ", "jju",
            "っじょ", "jjo",
            "っちゃ", "ccha",
            "っちゅ", "cchu",
            "っちょ", "ccho",
            "っにゃ", "nnya",
            "っにゅ", "nnyu",
            "っにょ", "nnyo",
            "っひゃ", "hhya",
            "っひゅ", "hhyu",
            "っひょ", "hhyo",
            "っびゃ", "bbya",
            "っびゅ", "bbyu",
            "っびょ", "bbyo",
            "っぴゃ", "ppya",
            "っぴゅ", "ppyu",
            "っぴょ", "ppyo",
            "っみゃ", "mmya",
            "っみゅ", "mmyu",
            "っみょ", "mmyo",
            "っりゃ", "rrya",
            "っりゅ", "rryu",
            "っりょ", "rryo",

            "っかあ", "kkā",
            "っきい", "kkī",
            "っくう", "kkū",
            "っけい", "kkei",
            "っけえ", "kkē",
            "っこう", "kkou",
            "っこお", "kkō",
            "っさあ", "ssā",
            "っしい", "sshī",
            "っすう", "ssū",
            "っせい", "ssei",
            "っせえ", "ssē",
            "っそう", "ssou",
            "っそお", "ssō",
            "ったあ", "ttā",
            "っちい", "cchī",
            "っつう", "ttsū",
            "ってい", "ttei",
            "ってえ", "ttē",
            "っとう", "ttou",
            "っとお", "ttō",
            "っなあ", "nnā",
            "っにい", "nnī",
            "っぬう", "nnū",
            "っねい", "nnei",
            "っねえ", "nnē",
            "っのう", "nnou",
            "っのお", "nnō",
            "っはあ", "hhā",
            "っひい", "hhī",
            "っふう", "ffū",
            "っへい", "hhei",
            "っへえ", "hhē",
            "っほう", "hhou",
            "っほお", "hhō",
            "っまあ", "mmā",
            "っみい", "mmī",
            "っむう", "mmū",
            "っめい", "mmei",
            "っめえ", "mmē",
            "っもう", "mmou",
            "っもお", "mmō",
            "っやあ", "yyā",
            "っゆう", "yyū",
            "っよう", "yyou",
            "っよお", "yyō",
            "っらあ", "rrā",
            "っりい", "rrī",
            "っるう", "rrū",
            "っれい", "rrei",
            "っれえ", "rrē",
            "っろう", "rrou",
            "っろお", "rrō",
            "っわあ", "wwā",
            "っがあ", "ggā",
            "っぎい", "ggī",
            "っぐう", "ggū",
            "っげい", "ggei",
            "っげえ", "ggē",
            "っごう", "ggou",
            "っごお", "ggō",
            "っざあ", "zzā",
            "っじい", "jjī",
            "っずう", "zzū",
            "っぜい", "zzei",
            "っぜえ", "zzē",
            "っぞう", "zzou",
            "っぞお", "zzō",
            "っだあ", "ddā",
            "っぢい", "ddzī",
            "っづう", "ddzū",
            "っでい", "ddei",
            "っでえ", "ddē",
            "っどう", "ddou",
            "っどお", "ddō",
            "っばあ", "bbā",
            "っびい", "bbī",
            "っぶう", "bbū",
            "っべい", "bbei",
            "っべえ", "bbē",
            "っぼう", "bbou",
            "っぼお", "bbō",
            "っぱあ", "ppā",
            "っぴい", "ppī",
            "っぷう", "ppū",
            "っぺい", "ppei",
            "っぺえ", "ppē",
            "っぽう", "ppou",
            "っぽお", "ppō",
            "っきゃあ", "kkyā",
            "っきゅう", "kkyū",
            "っきょう", "kkyou",
            "っきょお", "kkyō",
            "っぎゃあ", "ggyā",
            "っぎゅう", "ggyū",
            "っぎょう", "ggyou",
            "っぎょお", "ggyō",
            "っしゃあ", "sshā",
            "っしゅう", "sshū",
            "っしょう", "sshou",
            "っしょお", "sshō",
            "っじゃあ", "jjā",
            "っじゅう", "jjū",
            "っじょう", "jjou",
            "っじょお", "jjō",
            "っちゃあ", "cchā",
            "っちゅう", "cchū",
            "っちょう", "cchou",
            "っちょお", "cchō",
            "っにゃあ", "nnyā",
            "っにゅう", "nnyū",
            "っにょう", "nnyou",
            "っにょお", "nnyō",
            "っひゃあ", "hhyā",
            "っひゅう", "hhyū",
            "っひょう", "hhyou",
            "っひょお", "hhyō",
            "っびゃあ", "bbyā",
            "っびゅう", "bbyū",
            "っびょう", "bbyou",
            "っびょお", "bbyō",
            "っぴゃあ", "ppyā",
            "っぴゅう", "ppyū",
            "っぴょう", "ppyou",
            "っぴょお", "ppyō",
            "っみゃあ", "mmyā",
            "っみゅう", "mmyū",
            "っみょう", "mmyou",
            "っみょお", "mmyō",
            "っりゃあ", "rryā",
            "っりゅう", "rryū",
            "っりょう", "rryou",
            "っりょお", "rryō",

            "あい", "ai",

            /*
            "あっ", "as",
            "いっ", "is",
            "うっ", "us",
            "えっ", "es",
            "おっ", "os",
            "かっ", "kas",
            "きっ", "kis",
            "くっ", "kus",
            "けっ", "kes",
            "こっ", "kos",
            "さっ", "sas",
            "しっ", "shis",
            "すっ", "sus",
            "せっ", "ses",
            "そっ", "sos",
            "たっ", "tas",
            "ちっ", "chis",
            "つっ", "tsus",
            "てっ", "tes",
            "とっ", "tos",
            "なっ", "nas",
            "にっ", "nis",
            "ぬっ", "nus",
            "ねっ", "nes",
            "のっ", "nos",
            "はっ", "has",
            "ひっ", "his",
            "ふっ", "fus",
            "へっ", "hes",
            "ほっ", "hos",
            "まっ", "mas",
            "みっ", "mis",
            "むっ", "mus",
            "めっ", "mes",
            "もっ", "mos",
            "やっ", "yas",
            "ゆっ", "yus",
            "よっ", "yos",
            "らっ", "ras",
            "りっ", "ris",
            "るっ", "rus",
            "れっ", "res",
            "ろっ", "ros",
            "わっ", "was",
            "をっ", "wos",
            "がっ", "gas",
            "ぎっ", "gis",
            "ぐっ", "gus",
            "げっ", "ges",
            "ごっ", "gos",
            "ざっ", "zas",
            "じっ", "jis",
            "ずっ", "zus",
            "ぜっ", "zes",
            "ぞっ", "zos",
            "だっ", "das",
            "ぢっ", "dis",
            "づっ", "dus",
            "でっ", "des",
            "どっ", "dos",
            "ばっ", "bas",
            "びっ", "bis",
            "ぶっ", "bus",
            "べっ", "bes",
            "ぼっ", "bos",
            "ぱっ", "pas",
            "ぴっ", "pis",
            "ぷっ", "pus",
            "ぺっ", "pes",
            "ぽっ", "pos",
            "きゃっ", "kyas",
            "きゅっ", "kyus",
            "きょっ", "kyos",
            "ぎゃっ", "gyas",
            "ぎゅっ", "gyus",
            "ぎょっ", "gyos",
            "しゃっ", "shas",
            "しゅっ", "shus",
            "しょっ", "shos",
            "じゃっ", "jas",
            "じゅっ", "jus",
            "じょっ", "jos",
            "ちゃっ", "chas",
            "ちゅっ", "chus",
            "ちょっ", "chos",
            "にゃっ", "nyas",
            "にゅっ", "nyus",
            "にょっ", "nyos",
            "ひゃっ", "hyas",
            "ひゅっ", "hyus",
            "ひょっ", "hyos",
            "びゃっ", "byas",
            "びゅっ", "byus",
            "びょっ", "byos",
            "ぴゃっ", "pyas",
            "ぴゅっ", "pyus",
            "ぴょっ", "pyos",
            "みゃっ", "myas",
            "みゅっ", "myus",
            "みょっ", "myos",
            "りゃっ", "ryas",
            "りゅっ", "ryus",
            "りょっ", "ryos",
            */

            "ゑ", "we",
            "ゐ", "wi",

            "ぁ", "~a",
            "ぇ", "~e",
            "ぃ", "~i",
            "ぅ", "~u",
            "ぉ", "~o",
            "ゃ", "~ya",
            "ゅ", "~yu",
            "ょ", "~yo",
            "ゎ", "~wa",
            "っ", "~tsu",

            "ア", "a",
            "イ", "i",
            "ウ", "u",
            "エ", "e",
            "オ", "o",
            "カ", "ka",
            "キ", "ki",
            "ク", "ku",
            "ケ", "ke",
            "コ", "ko",
            "サ", "sa",
            "シ", "shi",
            "ス", "su",
            "セ", "se",
            "ソ", "so",
            "タ", "ta",
            "チ", "chi",
            "ツ", "tsu",
            "テ", "te",
            "ト", "to",
            "ナ", "na",
            "ニ", "ni",
            "ヌ", "nu",
            "ネ", "ne",
            "ノ", "no",
            "ハ", "ha",
            "ヒ", "hi",
            "フ", "fu",
            "ヘ", "he",
            "ホ", "ho",
            "マ", "ma",
            "ミ", "mi",
            "ム", "mu",
            "メ", "me",
            "モ", "mo",
            "ヤ", "ya",
            "ユ", "yu",
            "ヨ", "yo",
            "ラ", "ra",
            "リ", "ri",
            "ル", "ru",
            "レ", "re",
            "ロ", "ro",
            "ワ", "wa",
            "ヲ", "wo",
            "ン", "n",
            "ガ", "ga",
            "ギ", "gi",
            "グ", "gu",
            "ゲ", "ge",
            "ゴ", "go",
            "ザ", "za",
            "ジ", "ji",
            "ズ", "zu",
            "ゼ", "ze",
            "ゾ", "zo",
            "ダ", "da",
            "ヂ", "di",
            "ヅ", "du",
            "デ", "de",
            "ド", "do",
            "バ", "ba",
            "ビ", "bi",
            "ブ", "bu",
            "ベ", "be",
            "ボ", "bo",
            "ヴ", "vu",
            "パ", "pa",
            "ピ", "pi",
            "プ", "pu",
            "ペ", "pe",
            "ポ", "po",
            "キャ", "kya",
            "キュ", "kyu",
            "キョ", "kyo",
            "ギャ", "gya",
            "ギュ", "gyu",
            "ギョ", "gyo",
            "シャ", "sha",
            "シュ", "shu",
            "ショ", "sho",
            "シェ", "she",
            "ジャ", "ja",
            "ジュ", "ju",
            "ジョ", "jo",
            "ジェ", "je",
            "チャ", "cha",
            "チュ", "chu",
            "チョ", "cho",
            "ニャ", "nya",
            "ニュ", "nyu",
            "ニョ", "nyo",
            "ヒャ", "hya",
            "ヒュ", "hyu",
            "ヒョ", "hyo",
            "ビャ", "bya",
            "ビュ", "byu",
            "ビョ", "byo",
            "ピャ", "pya",
            "ピュ", "pyu",
            "ピョ", "pyo",
            "ミャ", "mya",
            "ミュ", "myu",
            "ミョ", "myo",
            "リャ", "rya",
            "リュ", "ryu",
            "リョ", "ryo",

            "アー", "ā",
            "イー", "ī",
            "ウー", "ū",
            "エー", "ē",
            "オー", "ō",
            "カー", "kā",
            "キー", "kī",
            "クー", "kū",
            "ケー", "kē",
            "コー", "kō",
            "サー", "sā",
            "シー", "shī",
            "スー", "sū",
            "セー", "sē",
            "ソー", "sō",
            "ター", "tā",
            "チー", "chī",
            "ツー", "tsū",
            "テー", "tē",
            "トー", "tō",
            "ナー", "nā",
            "ニー", "nī",
            "ヌー", "nū",
            "ネー", "nē",
            "ノー", "nō",
            "ハー", "hā",
            "ヒー", "hī",
            "フー", "fū",
            "ヘー", "hē",
            "ホー", "hō",
            "マー", "mā",
            "ミー", "mī",
            "ムー", "mū",
            "メー", "mē",
            "モー", "mō",
            "ヤー", "yā",
            "ユー", "yū",
            "ヨー", "yō",
            "ラー", "rā",
            "リー", "rī",
            "ルー", "rū",
            "レー", "rē",
            "ロー", "rō",
            "ワー", "wā",
            "ヲー", "wō",
            "ンー", "n",
            "ガー", "gā",
            "ギー", "gī",
            "グー", "gū",
            "ゲー", "gē",
            "ゴー", "gō",
            "ザー", "zā",
            "ジー", "jī",
            "ズー", "zū",
            "ゼー", "zē",
            "ゾー", "zō",
            "ダー", "dā",
            "ヂー", "dī",
            "ヅー", "dū",
            "デー", "dē",
            "ドー", "dō",
            "バー", "bā",
            "ビー", "bī",
            "ブー", "bū",
            "ベー", "bē",
            "ボー", "bō",
            "パー", "pā",
            "ピー", "pī",
            "プー", "pū",
            "ペー", "pē",
            "ポー", "pō",
            "キャー", "kyā",
            "キュー", "kyū",
            "キョー", "kyō",
            "ギャー", "gyā",
            "ギュー", "gyū",
            "ギョー", "gyō",
            "シャー", "shā",
            "シュー", "shū",
            "ショー", "shō",
            "ジャー", "jā",
            "ジュー", "jū",
            "ジョー", "jō",
            "チャー", "chā",
            "チュー", "chū",
            "チョー", "chō",
            "ニャー", "nyā",
            "ニュー", "nyū",
            "ニョー", "nyō",
            "ヒャー", "hyā",
            "ヒュー", "hyū",
            "ヒョー", "hyō",
            "ビャー", "byā",
            "ビュー", "byū",
            "ビョー", "byō",
            "ピャー", "pyā",
            "ピュー", "pyū",
            "ピョー", "pyō",
            "ミャー", "myā",
            "ミュー", "myū",
            "ミョー", "myō",
            "リャー", "ryā",
            "リュー", "ryū",
            "リョー", "ryō",

            "ティ", "ti",
            "ディ", "di",
            "デュ", "du",
            "ツァ", "tsa",
            "ファ", "fa",
            "フィ", "fi",
            "フェ", "fe",
            "フォ", "fo",
            "ヴァ", "va",
            "ヴィ", "vi",
            "ヴェ", "ve",
            "ヴォ", "vo",
            "ウィ", "wi",
            "ウェ", "we",
            "ウォ", "wo",
            "クィ", "qui",
            "クェ", "que",
            "クォ", "quo",
            "レィ", "rei",
            "アィ", "ai",
            "ティッ", "tis",
            "ディッ", "dis",
            "デュッ", "dus",
            "ツァッ", "tsas",
            "ファッ", "fas",
            "フィッ", "fis",
            "フェッ", "fes",
            "フォッ", "fos",
            "ヴァッ", "vas",
            "ヴィッ", "vis",
            "ヴェッ", "ves",
            "ヴォッ", "vos",
            "ウィッ", "wis",
            "ウェッ", "wes",
            "ウォッ", "wos",
            "クィッ", "quis",
            "クェッ", "ques",
            "クォッ", "quos",
            "レィッ", "reis",
            "アィッ", "ais",
            "ィッ", "is",
            "ゥッ", "us",

            "ヴア", "va",
            "ヴイ", "vi",
            "ヴエ", "ve",
            "ヴオ", "vo",
            "ヴアッ", "vas",
            "ヴイッ", "vis",
            "ヴエッ", "ves",
            "ヴオッ", "vos",

            /*
            "アッ", "as",
            "イッ", "is",
            "ウッ", "us",
            "エッ", "es",
            "ョッ", "os",
            "カッ", "kas",
            "キッ", "kis",
            "クッ", "kus",
            "ケッ", "kes",
            "コッ", "kos",
            "サッ", "sas",
            "シッ", "shis",
            "スッ", "sus",
            "セッ", "ses",
            "ソッ", "sos",
            "タッ", "tas",
            "チッ", "chis",
            "ツッ", "tsus",
            "テッ", "tes",
            "トッ", "tos",
            "ナッ", "nas",
            "ニッ", "nis",
            "ヌッ", "nus",
            "ネッ", "nes",
            "ノッ", "nos",
            "ハッ", "has",
            "ヒッ", "his",
            "フッ", "fus",
            "ヘッ", "hes",
            "ホッ", "hos",
            "マッ", "mas",
            "ミッ", "mis",
            "ムッ", "mus",
            "メッ", "mes",
            "モッ", "mos",
            "ヤッ", "yas",
            "ユッ", "yus",
            "ヨッ", "yos",
            "ラッ", "ras",
            "リッ", "ris",
            "ルッ", "rus",
            "レッ", "res",
            "ロッ", "ros",
            "ワッ", "was",
            "ヲッ", "wos",
            "ガッ", "gas",
            "ギッ", "gis",
            "グッ", "gus",
            "ゲッ", "ges",
            "ゴッ", "gos",
            "ザッ", "zas",
            "ジッ", "jis",
            "ズッ", "zus",
            "ゼッ", "zes",
            "ゾッ", "zos",
            "ダッ", "das",
            "ヂッ", "dis",
            "ヅッ", "dus",
            "デッ", "des",
            "ドッ", "dos",
            "バッ", "bas",
            "ビッ", "bis",
            "ブッ", "bus",
            "ベッ", "bes",
            "ボッ", "bos",
            "パッ", "pas",
            "ピッ", "pis",
            "プッ", "pus",
            "ペッ", "pes",
            "ポッ", "pos",
            "キャッ", "kyas",
            "キュッ", "kyus",
            "キョッ", "kyos",
            "ギャッ", "gyas",
            "ギュッ", "gyus",
            "ギョッ", "gyos",
            "シャッ", "shas",
            "シュッ", "shus",
            "ショッ", "shos",
            "ジャッ", "jas",
            "ジュッ", "jus",
            "ジョッ", "jos",
            "チャッ", "chas",
            "チュッ", "chus",
            "チョッ", "chos",
            "ニャッ", "nyas",
            "ニュッ", "nyus",
            "ニョッ", "nyos",
            "ヒャッ", "hyas",
            "ヒュッ", "hyus",
            "ヒョッ", "hyos",
            "ビャッ", "byas",
            "ビュッ", "byus",
            "ビョッ", "byos",
            "ピャッ", "pyas",
            "ピュッ", "pyus",
            "ピョッ", "pyos",
            "ミャッ", "myas",
            "ミュッ", "myus",
            "ミョッ", "myos",
            "リャッ", "ryas",
            "リュッ", "ryus",
            "リョッ", "ryos",
            */

            "ティー", "tī",
            "ディー", "dī",
            "デュー", "dū",
            "ツァー", "tsā",
            "ファー", "fā",
            "フィー", "fī",
            "フェー", "fē",
            "フォー", "fō",
            "ヴァー", "vā",
            "ヴィー", "vī",
            "ヴェー", "vē",
            "ヴォー", "vō",
            "ウィー", "wī",
            "ウェー", "wē",
            "ウォー", "wō",
            "クィー", "quī",
            "クェー", "quē",
            "クォー", "quō",

            "ヱ", "we",
            "ヰ", "wi",

            "ッカ", "kka",
            "ッキ", "kki",
            "ック", "kku",
            "ッケ", "kke",
            "ッコ", "kko",
            "ッサ", "ssa",
            "ッシ", "sshi",
            "ッス", "ssu",
            "ッセ", "sse",
            "ッソ", "sso",
            "ッタ", "tta",
            "ッチ", "cchi",
            "ッツ", "ttsu",
            "ッテ", "tte",
            "ット", "tto",
            "ッナ", "nna",
            "ッニ", "nni",
            "ッヌ", "nnu",
            "ッネ", "nne",
            "ッノ", "nno",
            "ッハ", "hha",
            "ッヒ", "hhi",
            "ッフ", "ffu",
            "ッヘ", "hhe",
            "ッホ", "hho",
            "ッマ", "mma",
            "ッミ", "mmi",
            "ッム", "mmu",
            "ッメ", "mme",
            "ッモ", "mmo",
            "ッヤ", "yya",
            "ッユ", "yyu",
            "ッヨ", "yyo",
            "ッラ", "rra",
            "ッリ", "rri",
            "ッル", "rru",
            "ッレ", "rre",
            "ッロ", "rro",
            "ッワ", "wwa",
            "ッヲ", "wwo",
            "ッン", "nn",
            "ッガ", "gga",
            "ッギ", "ggi",
            "ッグ", "ggu",
            "ッゲ", "gge",
            "ッゴ", "ggo",
            "ッザ", "zza",
            "ッジ", "jji",
            "ッズ", "zzu",
            "ッゼ", "zze",
            "ッゾ", "zzo",
            "ッダ", "dda",
            "ッヂ", "ddi",
            "ッヅ", "ddu",
            "ッデ", "dde",
            "ッド", "ddo",
            "ッバ", "bba",
            "ッビ", "bbi",
            "ッブ", "bbu",
            "ッベ", "bbe",
            "ッボ", "bbo",
            "ッヴ", "vvu",
            "ッパ", "ppa",
            "ッピ", "ppi",
            "ップ", "ppu",
            "ッペ", "ppe",
            "ッポ", "ppo",
            "ッキャ", "kkya",
            "ッキュ", "kkyu",
            "ッキョ", "kkyo",
            "ッギャ", "ggya",
            "ッギュ", "ggyu",
            "ッギョ", "ggyo",
            "ッシャ", "ssha",
            "ッシュ", "sshu",
            "ッショ", "ssho",
            "ッシェ", "sshe",
            "ッジャ", "jja",
            "ッジュ", "jju",
            "ッジョ", "jjo",
            "ッジェ", "jje",
            "ッチャ", "ccha",
            "ッチュ", "cchu",
            "ッチョ", "ccho",
            "ッニャ", "nnya",
            "ッニュ", "nnyu",
            "ッニョ", "nnyo",
            "ッヒャ", "hhya",
            "ッヒュ", "hhyu",
            "ッヒョ", "hhyo",
            "ッビャ", "bbya",
            "ッビュ", "bbyu",
            "ッビョ", "bbyo",
            "ッピャ", "ppya",
            "ッピュ", "ppyu",
            "ッピョ", "ppyo",
            "ッミャ", "mmya",
            "ッミュ", "mmyu",
            "ッミョ", "mmyo",
            "ッリャ", "rrya",
            "ッリュ", "rryu",
            "ッリョ", "rryo",

            "ァ", "~a",
            "ィ", "~i",
            "ゥ", "~u",
            "ェ", "~e",
            "ォ", "~o",
            "ヵ", "~ka",
            "ㇰ", "~ku",
            "ヶ", "~ke",
            "ㇱ", "~shi",
            "ㇲ", "~su",
            "ッ", "~tsu",
            "ㇳ", "~to",
            "ㇴ", "~nu",
            "ㇵ", "~ha",
            "ㇶ", "~hi",
            "ㇷ", "~fu",
            "ㇷ゚", "~pu",
            "ㇸ", "~he",
            "ㇹ", "~ho",
            "ㇺ", "~mu",
            "ャ", "~ya",
            "ュ", "~yu",
            "ョ", "~yo",
            "ㇻ", "~ra",
            "ㇼ", "~ri",
            "ㇽ", "~ru",
            "ㇾ", "~re",
            "ㇿ", "~ro",
            "ヮ", "~wa",
            "ー", "",

            "ゝ", "~a",
            "ゞ", "",
            "ヽ", "",
            "ヾ", "",
        };

        public static char[] TheCharacters =
        {
            'あ',
            'い',
            'う',
            'え',
            'お',
            'か',
            'き',
            'く',
            'け',
            'こ',
            'さ',
            'し',
            'す',
            'せ',
            'そ',
            'た',
            'ち',
            'つ',
            'て',
            'と',
            'な',
            'に',
            'ぬ',
            'ね',
            'の',
            'は',
            'ひ',
            'ふ',
            'へ',
            'ほ',
            'ま',
            'み',
            'む',
            'め',
            'も',
            'や',
            'ゆ',
            'よ',
            'ら',
            'り',
            'る',
            'れ',
            'ろ',
            'わ',
            'を',
            'ん',
            'が',
            'ぎ',
            'ぐ',
            'げ',
            'ご',
            'ざ',
            'じ',
            'ず',
            'ぜ',
            'ぞ',
            'だ',
            'ぢ',
            'づ',
            'で',
            'ど',
            'ば',
            'び',
            'ぶ',
            'べ',
            'ヴ',
            'ぼ',
            'ぱ',
            'ぴ',
            'ぷ',
            'ぺ',
            'ぽ',
            'ゑ',
            'ゐ',
            'ぁ',
            'ぇ',
            'ぃ',
            'ぉ',
            'ぅ',
            'ゃ',
            'ょ',
            'ゅ',
            'ゎ',
            'っ',
            'ア',
            'イ',
            'ウ',
            'エ',
            'オ',
            'カ',
            'キ',
            'ク',
            'ケ',
            'コ',
            'サ',
            'シ',
            'ス',
            'セ',
            'ソ',
            'タ',
            'チ',
            'ツ',
            'テ',
            'ト',
            'ナ',
            'ニ',
            'ヌ',
            'ネ',
            'ノ',
            'ハ',
            'ヒ',
            'フ',
            'ヘ',
            'ホ',
            'マ',
            'ミ',
            'ム',
            'メ',
            'モ',
            'ヤ',
            'ユ',
            'ヨ',
            'ラ',
            'リ',
            'ル',
            'レ',
            'ロ',
            'ワ',
            'ヲ',
            'ン',
            'ガ',
            'ギ',
            'グ',
            'ゲ',
            'ゴ',
            'ザ',
            'ジ',
            'ズ',
            'ゼ',
            'ゾ',
            'ダ',
            'ヂ',
            'ヅ',
            'デ',
            'ド',
            'バ',
            'ビ',
            'ブ',
            'ベ',
            'ボ',
            'パ',
            'ピ',
            'プ',
            'ペ',
            'ポ',
            'ャ',
            'ュ',
            'ョ',
            'ー',
            'ヰ',
            'ヱ',
            'ァ',
            'ィ',
            'ェ',
            'ォ',
            'ゥ',
            'ヮ',
            'ヶ',
            'ッ',
            'ゝ',
            'ゞ',
            'ヽ',
            'ヾ'
        };

        public static char[] KatakanaCharacters =
        {
            'ア',
            'イ',
            'ウ',
            'エ',
            'オ',
            'カ',
            'キ',
            'ク',
            'ケ',
            'コ',
            'サ',
            'シ',
            'ス',
            'セ',
            'ソ',
            'タ',
            'チ',
            'ツ',
            'テ',
            'ト',
            'ナ',
            'ニ',
            'ヌ',
            'ネ',
            'ノ',
            'ハ',
            'ヒ',
            'フ',
            'ヘ',
            'ホ',
            'マ',
            'ミ',
            'ム',
            'メ',
            'モ',
            'ヤ',
            'ユ',
            'ヨ',
            'ラ',
            'リ',
            'ル',
            'レ',
            'ロ',
            'ワ',
            'ヲ',
            'ン',
            'ガ',
            'ギ',
            'グ',
            'ゲ',
            'ゴ',
            'ザ',
            'ジ',
            'ズ',
            'ゼ',
            'ゾ',
            'ダ',
            'ヂ',
            'ヅ',
            'デ',
            'ド',
            'バ',
            'ビ',
            'ブ',
            'ベ',
            'ボ',
            'パ',
            'ピ',
            'プ',
            'ペ',
            'ポ',
            'ャ',
            'ュ',
            'ョ',
            'ー',
            'ヰ',
            'ヱ',
            'ァ',
            'ィ',
            'ェ',
            'ォ',
            'ゥ',
            'ヮ',
            'ヶ',
            'ッ',
            'ゝ',
            'ゞ',
            'ヽ',
            'ヾ'
        };

        public static char[] RomajiCharacters =
        {
            'a',
            'b',
            'c',
            'd',
            'e',
            'f',
            'g',
            'h',
            'i',
            'j',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'q',
            'r',
            's',
            't',
            'u',
            'v',
            'w',
            'x',
            'y',
            'z',
            'ā',
            'ē',
            'ī',
            'ō',
            'ū',
            'A',
            'B',
            'C',
            'D',
            'E',
            'F',
            'G',
            'H',
            'I',
            'J',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'Q',
            'R',
            'S',
            'T',
            'U',
            'V',
            'W',
            'X',
            'Y',
            'Z',
            'Ā',
            'Ē',
            'Ī',
            'Ō',
            'Ū'
        };

        public static Dictionary<string, string> TheTableDictionary
        {
            get
            {
                if (_TheTableDictionary == null)
                    _TheTableDictionary = GetDictionaryFromTablePairs(TheTablePairs);

                return _TheTableDictionary;
            }
            set
            {
                _TheTableDictionary = value;
            }
        }

        public static HashSet<char> TheCharacterSet
        {
            get
            {
                if (_TheCharacterSet == null)
                    _TheCharacterSet = GetCharacterSetFromCharacters(TheCharacters);

                return _TheCharacterSet;
            }
            set
            {
                _TheCharacterSet = value;
            }
        }

        public static int TheMaxInputLength
        {
            get
            {
                if (_TheMaxInputLength == -1)
                    _TheMaxInputLength = GetMaxInputLengthFromTablePairs(TheTablePairs);

                return _TheMaxInputLength;
            }
            set
            {
                _TheMaxInputLength = value;
            }
        }

        public static int TheMaxOutputLength
        {
            get
            {
                if (_TheMaxOutputLength == -1)
                    _TheMaxOutputLength = GetMaxOutputLengthFromTablePairs(TheTablePairs);

                return _TheMaxOutputLength;
            }
            set
            {
                _TheMaxOutputLength = value;
            }
        }
    }
}
